# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e355d5ab03893ce3645d52352bc87169cde107c64aab1a4a062db9a91034336ff6540a69148e8655b5d037b9a47f059250e903f8711cb7b4090b37a22634fce

test:
  secret_key_base: 11eacd34e258e34b9ca33a9161f5f68bcbfb0b5bd6d5ece37e60b1e6300e4715d52779915d648ac3cad7c8d835b1089835201e03ac425fc0c05f40c2d2aaac4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
